### PR TITLE
Clarify the attribution and license of the project

### PR DESCRIPTION
**Pull request by mrkvon**
This codebase was originally developed as part of the Open Hospitality Network (OHN) and has been [subsequently relicensed](https://github.com/solidcouch/solidcouch/commit/1ca1193366ff5b1f5feede182f24d64ea3a9f178#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7) to SolidCouch under the [current license](https://github.com/solidcouch/solidcouch/blob/main/LICENSE) (MIT). Any remaining files that are still licensed under OHN retain their [original license](https://github.com/solidcouch/solidcouch/blob/6a75684ba36410c5213b1d815cdddc6361643006/LICENSE) (MIT), and these files are clearly marked with the original OHN license.

This change is necessary to address missing consent with the relicensing.

Approaches:
- Include previous license in relevant files
- Remove code

### CODE REVIEW

**Comment by mariha** [comment]
The codebase is a whole and it was taken without authorisation from OHN to SolidCouch. Afaik, it is illegal to relicense the code without explicit consent of all the contributors / co-authors of that codebase.

This change is illegal as well. Although @mrkvon authored most of the code, there is a difference between authorship and ownership and it has not been recognized here.

**Comment by mrkvon** [comment]
@mariha Thank you for expressing your concerns. I understand that this is an important matter to you, and I want to address your points thoughtfully.

Regarding your statement that the codebase was "taken without authorization" and that it is illegal to relicense it without explicit consent, it’s important to clarify that under copyright law, contributors retain ownership of their individual contributions unless they have signed over rights to the organization. Since we haven’t signed any agreements assigning our rights to the Open Hospitality Network (OHN), each of us holds the copyright to our own code.

You’re absolutely right that there’s a distinction between authorship and ownership. **I fully recognize and respect your ownership over your contributions**, which is why I have proposed two solutions:

- **Removal of your contributions**: As mentioned, I’m prepared to remove your code from the repository entirely if you prefer not to consent to the re-licensing.
- **Retaining the original license**: For any files you fully authored, I have ensured that the original OHN license remains intact.

The steps I’ve taken are aimed at fully respecting both your ownership and the licensing terms. If there’s anything further that we can do to address your concerns, I’m happy to continue working toward a resolution that aligns with legal and community standards.

**Comment by mariha** [comment]
I have different information about codebase being a whole not a set of individual and independent contributions.

I was not the only co-author of this codebase.

GitHub repo is more then a codebase: it's a community that was built around it, people who follow changes to it, history of issues and the thing itself that was created and is owned by OHN. You didn't have rights to move the repo to the different organization.

**Comment by mrkvon** [comment]
@mariha Thank you for your input. The PR focuses solely on the licensing of the codebase. All contributions not authored by me have either been removed or remain under the original OHN license. The matter of the GitHub repository move is a separate issue and out of scope for this PR.

I suggest we close this discussion here and address any further concerns in a more appropriate context.

**Pull request merged**
